### ISSUE TITLE
Wiring for flashing with STlink V2?

### ISSUE THREAD

**Issue by chepo92** [davidtgbe/Marlin#13]
@davidtgbe 
Which is the wiring to upload and flash the bootloader with STlink V2? 
I see the marks V (or U) and G on the board (I guess that is the SWIO header), assuming they are Vcc (guess connect it to 3.3v and not 5V), G to GND, but what about the rest?
If it is as the bluepill it should be Vcc, DIO, CLK and GNG (U-G)

**Comment by muhla89** [comment]
G, Swdio , swclk

**Comment by chepo92** [comment]
https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config/examples/Anet/ET5X  

SWD Header on ET Series motherboard
```
     ___
  U | o |  (not connected)
    |---|
    | o |  SWDIO
    |---|
    | o |  SWCLCK
    |---|
  G | o |  GND
     ---
```
