### ISSUE TITLE
Feature Request BL_Touch for ET4X?

### ISSUE THREAD

**Issue by ArcAIN6** [davidtgbe/Marlin#14]
Not too sure what, if any, differences there are between mainboards, and the breakout board of the ET4 and ET4X. 

Looking over the steps of trying to add a BLtouch sensor to the ET4X i have by looking through this guide, and the marlin you've posted here, and it appears there's no support as of yet, for adding a BLtouch probe to the ET4X.

Is it possible to do so? And if so, what would i need to change in the marlin configs to make it happen? 
(appears that using easyconfig doesn't support ET4X with BLtouch)

Thanks in advance for reading this, looking forward to any insights you might have. 

Thanks :)

**Comment by davidtgbe** [comment]
Yes, it is possible. Easyconfig allows enabling both bltouch and ET4X. Just read carefully instructions on easyconfig and follow the bltouch tutorial. You can also ask on telegram anetet4esp telegram group.
