### ISSUE TITLE
How do i build this for the ET4X?

### ISSUE THREAD

**Issue by ArcAIN6** [davidtgbe/Marlin#16]
Trying to build this for ET4X, yet it keeps building for ET4, and i'm unsure why. 

In easyconfig.h, i set ET_MODEL to ET_MODEL_ET4X
Built the project, flashed the firmware, it comes up showing ET4, not ET4X, and homes in the wrong direction. 

Looked over EasyConfig again, and changed the direction it homes to down, but still, it want's to home upwards. 

Am i missing something here?

**Comment by davidtgbe** [comment]
@ArcAIN6 This is not an issue. You only have to follow readme and easyconfig instructions.
https://github.com/davidtgbe/Marlin/blob/5b73b5dc17f349debca18b5663e7dab8f18583d2/Marlin/EasyConfig.h#L39
