### ISSUE TITLE
Howto compile for an Anet ET4-Pro?

### ISSUE THREAD

**Issue by Asxetos21** [davidtgbe/Marlin#19]
This is not an issue (sorry), but i hope i get a solid answer on the way to proceed.

What needs to be done (config-wise) to compile for an Anet ET4-Pro?

1. Simply editing EasyConfig.h on this repo for the printer model is enough? (so the rest of the config files read this and auto-set everything?) Or do Configuration.h and Configuration_adv.h need adjusting also?

2. Using the configuration example for Anet ET4-Pro on Marlin repo? The configs are very recent, but no idea if they are correct. (https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.0.x/config/examples/Anet/ET4-Pro)

Thanks...

**Comment by davidtgbe** [comment]
1.You can just use easyconfig. It will work. Just read instructions on easyconfig file.
Aditionally, you can change advanced parameters in configuration.h and configuraron_adv.h to better fit your needings. Just make sure these parameters are not listed at the bottom of the easyconfig file (listed as overwritten parameters).
2. User configs folder is outdated. It is just the contribution of some users when this project started which helped with the task of getting a working configuration for all the ET models.

I will clarify these points in the readme to avoid misunderstandings..
