### ISSUE TITLE
USB disconnection

### ISSUE THREAD

**Issue by Ghrem** [davidtgbe/Marlin#21]
USB disconnects constantly during printing when printing from Octoprint or even just being connected and having it print from SD, without having the safety timer on print head movement enabled it WILL stay heated on the part in last position of movement. I've tried multiple things to remedy it, but it persists. I'm wondering if it's related to https://github.com/MarlinFirmware/Marlin/pull/19671

ET4-MB_V1.1 in an ET5 X, using a Discovery board to flash the firmware. I've tried lowering the baud rate, disabling SD, disabling WATCHDOG, changed all sorts of random other settings that I can't even remember anymore. The issue keeps persisting.

Recv: //action:notification 17% L=-/-
Recv: ok
Send: M105
Recv: ok T:230.44 /230.00 B:54.86 /55.00 @:84 B@:0
Send: M27
Recv: SD printing byte 617557/3595118
Recv: ok
Recv: X:149.02 Y:142.68 Z:3.25 E:0.00 Count X:11420 Y:11885 Z:1300
Unexpected error while reading serial port, please consult octoprint.log for details: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:3860
Please see https://faq.octoprint.org/serialerror for possible reasons of this.

[Configuration.zip](https://github.com/davidtgbe/Marlin/files/6757597/Configuration.zip)

**Comment by davidtgbe** [comment]
AFAIK, no one else is having problems with Octoprint/USB. I do use Octoprint indeed. Try using Anet stock FW to discard a HW issue.
