### ISSUE TITLE
serial pin error when compiling for drivers TMC2208

### ISSUE THREAD

**Issue by manotroll** [davidtgbe/Marlin#23]
when trying to compile for TMC2208 drivers get this error

In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\HAL.cpp:28:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2502:4: error: #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
 2502 |   #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\HAL_SPI.cpp:25:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2502:4: error: #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
 2502 |   #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\MarlinSerial.cpp:21:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2502:4: error: #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
 2502 |   #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\Sd2Card_sdio_stm32duino.cpp:24:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2502:4: error: #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
 2502 |   #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\Servo.cpp:25:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2502:4: error: #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
 2502 |   #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_sdcard.cpp:28:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2502:4: error: #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
 2502 |   #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_flash.cpp:25:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2502:4: error: #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
 2502 |   #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
      |    ^~~~~
*** [.pio\build\ET4\src\src\HAL\STM32\HAL.cpp.o] Error 1
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_wired.cpp:25:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2502:4: error: #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
 2502 |   #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\eeprom_sram.cpp:25:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2502:4: error: #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
 2502 |   #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\tft\../../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\tft\gt911.cpp:24:
Marlin\src\HAL\STM32\tft\../../../inc/SanityCheck.h:2502:4: error: #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
 2502 |   #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
      |    ^~~~~
*** [.pio\build\ET4\src\src\HAL\STM32\MarlinSerial.cpp.o] Error 1
*** [.pio\build\ET4\src\src\HAL\STM32\HAL_SPI.cpp.o] Error 1
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\fastio.cpp:25:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2502:4: error: #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
 2502 |   #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\tft\../../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\tft\tft_ltdc.cpp:24:
Marlin\src\HAL\STM32\tft\../../../inc/SanityCheck.h:2502:4: error: #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
 2502 |   #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
      |    ^~~~~
*** [.pio\build\ET4\src\src\HAL\STM32\Sd2Card_sdio_stm32duino.cpp.o] Error 1
*** [.pio\build\ET4\src\src\HAL\STM32\Servo.cpp.o] Error 1
In file included from Marlin\src\HAL\STM32\../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\timers.cpp:24:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2502:4: error: #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
 2502 |   #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\tft\../../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\tft\tft_fsmc.cpp:24:
Marlin\src\HAL\STM32\tft\../../../inc/SanityCheck.h:2502:4: error: #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
 2502 |   #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
      |    ^~~~~
*** [.pio\build\ET4\src\src\HAL\STM32\eeprom_sdcard.cpp.o] Error 1
*** [.pio\build\ET4\src\src\HAL\STM32\eeprom_flash.cpp.o] Error 1
In file included from Marlin\src\HAL\STM32\tft\../../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\tft\xpt2046.cpp:24:
Marlin\src\HAL\STM32\tft\../../../inc/SanityCheck.h:2502:4: error: #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
 2502 |   #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
      |    ^~~~~
In file included from Marlin\src\HAL\STM32\tft\../../../inc/MarlinConfig.h:49,
                 from Marlin\src\HAL\STM32\tft\tft_spi.cpp:24:
Marlin\src\HAL\STM32\tft\../../../inc/SanityCheck.h:2502:4: error: #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."
 2502 |   #error "TMC2208 or TMC2209 on X requires X_HARDWARE_SERIAL or X_SERIAL_(RX|TX)_PIN."

**Comment by davidtgbe** [comment]
Tmc2208 is for using with uart which is not supported.
You have to use TMC2208_standalone
