### ISSUE TITLE
G29, M48 and Easyconfig not working

### ISSUE THREAD

**Issue by santiis2010** [davidtgbe/Marlin#24]
### Description

When i flash the firmware using easyconfig.h and Visual Studio Code, the firmware compiles without any issue, so i coppy all the files to the SD but im having this problems, G29 getting out of bound error, stepper motors not changing to silent (i have ET4P silent board for my ET5) if i do a M206 to fix the X and Y Min for example Y its already -15 i want it to be -22 so i put on pronter face M206 Y-22 i get on the printer Y-32 instead of Y-22.

### Steps to Reproduce

1. Dowload Marling 2.0 bug fix for Anet ET5, configure easyconfig.h and compile without errors
2. Flashing the ET5 printer with silent board, flash process its ok
3. Doing G28 works perfect, then G29 stops at first probe.

**Expected behavior: With G29 it has to do all the 9 probe points, motor drivers to be TCM2208 stand alone

**Actual behavior: Printer stops at first probe point, some times at the 6 probe point with error "Probe out of bounds", motor drivers shown as regular A4988

#### Additional Information
- I tried to configurate configuration.h at the same time using easyconfig.h to fix the motor steppers to TCM2208 Stand Alone and to fix board not changing to ET4P instead of ET4MB

Printer was working just fine, i needed to update it because i fixed the leng of the 
* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

[Marlin.zip](https://github.com/davidtgbe/Marlin/files/7078952/Marlin.zip)

**Comment by davidtgbe** [comment]
Hello Santiago,
should be working fine. If you edit with VS CODE Marlin\src\inc\EasyConfigPost.h, you can check which parameters are currently used (light font style) and unused (shadow/greyed out font style) as in the screen capture below using your config files:
https://github.com/davidtgbe/Marlin/blob/a6c0bcb42a9162d8f63363420b17a42b6700fbd7/Marlin/src/inc/EasyConfigPost.h

![image](https://user-images.githubusercontent.com/3966235/131659240-ceffc164-d9f2-4f61-b9db-87940900dca1.png)

As you can see, TMC2208_STANDALONE drivers are assigned.

I have noticed you have changed some parameters in configuration.h, which, easyconfig will just be overridden. You can find more info in comments at the end of the easyconfig.h file:
https://github.com/davidtgbe/Marlin/blob/a6c0bcb42a9162d8f63363420b17a42b6700fbd7/Marlin/EasyConfig.h#L185-L280

For example, you can't change print area by modifying size parameters in configuration.h file if you use easyconfig.h, because easyconfig will just overwrite these settings here:
https://github.com/davidtgbe/Marlin/blob/a6c0bcb42a9162d8f63363420b17a42b6700fbd7/Marlin/src/inc/EasyConfigPost.h#L281-L321

I recommend you to do this test to isolate problems:
- Redownload this repo
- Uncomment the line ```#define ET_EASY_CONFIG``` on configuration.h
- Paste your custom easyconfig.h file (or modify it according to your printer) and change the ```#define ET_CUSTOM_MACHINE_NAME``` to some custom name like "ET5 SANTIAGO TMC2208" which let you know that easyconfig has taken effect.
- Build and flash
- Follow post-installation steps below: https://github.com/davidtgbe/Marlin/blob/a6c0bcb42a9162d8f63363420b17a42b6700fbd7/Marlin/EasyConfig.h#L137-L164

Let me know if drivers are assigned correctly and M503 is reflecting your changes.

**Comment by santiis2010** [comment]
> Hello Santiago,
> should be working fine. If you edit with VS CODE Marlin\src\inc\EasyConfigPost.h, you can check which parameters are currently used (light font style) and unused (shadow/greyed out font style) as in the screen capture below using your config files:
> https://github.com/davidtgbe/Marlin/blob/a6c0bcb42a9162d8f63363420b17a42b6700fbd7/Marlin/src/inc/EasyConfigPost.h
> 
> ![image](https://user-images.githubusercontent.com/3966235/131659240-ceffc164-d9f2-4f61-b9db-87940900dca1.png)
> 
> As you can see, TMC2208_STANDALONE drivers are assigned.
> 
> I have noticed you have changed some parameters in configuration.h, which, easyconfig will just get overrided. You can find more info in comments at the end of the easyconfig.h file:
> https://github.com/davidtgbe/Marlin/blob/a6c0bcb42a9162d8f63363420b17a42b6700fbd7/Marlin/EasyConfig.h#L185-L280
> 
> For example, you can't change print area by modifying size parameters in configuration.h file if you use easyconfig.h, because easyconfig will just overwrite these settings here:
> https://github.com/davidtgbe/Marlin/blob/a6c0bcb42a9162d8f63363420b17a42b6700fbd7/Marlin/src/inc/EasyConfigPost.h#L281-L321
> 
> I recommend you to do this test to isolate problems:
> 
> * Redownload this repo
> * Uncomment the line `#define ET_EASY_CONFIG` on configuration.h
> * Paste your custom easyconfig.h file (or modify it according to your printer) and change the `#define ET_CUSTOM_MACHINE_NAME` to some custom name like "ET5 SANTIAGO TMC2208" which let you know that easyconfig has taken effect.
> * Build and flash
> * Follow post-installation steps below: https://github.com/davidtgbe/Marlin/blob/a6c0bcb42a9162d8f63363420b17a42b6700fbd7/Marlin/EasyConfig.h#L137-L164
> 
> Let me know if drivers are assigned correctly and M503 is reflecting your changes.

So i did al this, the only things i changed on easyconfigpost.h was the offset of the bed and X axis (X-3 and Y-22) and the steps from E0 to 98..68 i moved the extruder to direct drive.

(its ok if i can write in spanish?)

So i compiled everything, formated a 8GB card (not the one that came with the printer), inserted the micro SD card on the printer, so BTL started to update the firmware.

I connected the printer with windows 10, and pronterface, i sent m502 and then m500, set the M851 X-24 Y-8.7 and Z0, pids are just fine, everything worked like a charm till now... So i sent G28 and on the LCD screen of the printer (while doing home) i can see that X and Y gives me this numbers while moving the axis "X-529 and Y-483 (weird) but when finish homing it says X-3 and Y-22.

Then i sent G29, it goes to the middle, just fine, then when its going to do the firs probe point 1/9 the Z axis on the lcd screen says Z-2 and the printer stop doing ABL, on Pronterface o get this error message:

SENDING:G29
echo:busy: processing
echo:busy: processing
//action:notification Sondeo Fallado
Error:Probing Failed
[ERROR] Error:Probing Failed

//action:notification ET5 Silenciosa Santiago Lista
ok P7 B2

Also when i do M48 the first time before i sent the G29 the probe works but on the LCD screen Z axis says Z-2, so the probe its doing auto leveling and M48 at z-2 or something like that.

I attached againg the new files.
[Marlin.zip](https://github.com/davidtgbe/Marlin/files/7092793/Marlin.zip)

**Comment by davidtgbe** [comment]
> So i compiled everything, formated a 8GB card (not the one that came with the printer), inserted the micro SD card on the printer, so BTL started to update the firmware.

OK

>  connect the printer with windows 10, and pronterface, i send m502 and then m500, set the M851 X-24 Y-8.7 and Z0, pids are just fine, everything worked like a charm till now... 

Aquí un par de cosas:
- M502 para borrar, después el M851 para establecer la distancia entre la punta de sondeo y la punta del hotend y por último, el M500 para guardar, ese es el orden. 
- Si has puesto Z0 es que tienes la sonda a la misma altura que el hotend? Esto me parece raro... No es lo normal. Lo normal es tener la sonda por encima del hotend. Puedes ver este video para usar el asistente de offset en Z. https://youtu.be/fN_ndWvXGBQ?t=411

> So i send G28 and on the LCD screen for the printer while doing home i can see that X and Y gives me this numbres while moving the axis "X-529 and Y-483 (wierd) but when finish the homing it says X-3 and Y-22.

Con el primer home, lo importante es que se inicialicen y se hagan corresponder el home de X, Y, y Z con el offset marcado (-3 y -22). Si al finalizar el home es lo que te marca, es correcto.

> Then i send G29, it goes to the middle, just fine, then when its going to do the firs probe point 1/9 the Z axis on the lcd screen says Z-2 and the printer stop doing ABL, on Pronterface o get this error message:
> 
> SENDING:G29
> echo:busy: processing
> echo:busy: processing
> //action:notification Sondeo Fallado
> Error:Probing Failed
> [ERROR] Error:Probing Failed
> 
> //action:notification ET5 Silenciosa Santiago Lista
> ok P7 B2

Veo que el nombre de la impresora te lo está recogiendo correctamente del easyconfig. Entiendo que el resto de parámetros también (como los drivers que comentabas al principio). 
Veo también el error, pero es poco detallado. Llegados a este punto, si con lo anterior no se te soluciona, una prueba más que puedes hacer es usar bilinear (es lo que yo uso y no tengo pegas), aunque no creo que sea ese el problema.

> Also when i do M48 the first time before i sent the G29 the probe works but on the LCD screen Z axis says Z-2, so the probe its doing auto leveling and M48 at z-2 or something like that.

Con el M48 también me marcar a mi Z -2 ahora que lo he mirado, cuando el bltouch baja. No creo que sea un problema ni significativo. 

Puede que tu problema tenga que ver con el margen de seguridad a la hora de hacer el sondeo. Comprueba el margen de seguridad (PROBING_MARGIN). Se define en el configuration.h, y si no está definido, se establece a 25 mm para sondas inductivas/bltouch en el easyconfigpost.h. El hotend no puede salir de los márgenes definidos por el área de la cama menos el PROBING_MARGIN si mal no recuerdo. Prueba a ponerlo a 0 xej. 

Comprueba también con un M503 siempre después de cambiar algo y salvarlo con M500.

Envía una captura del M503 si después de todo te sigue sin funcionar y adjunta también los cambios que haces en el easyconfigpost.h
Hablamos en Español, no hay problema

**Comment by davidtgbe** [comment]
Hola Santiago, al final, diste con el problema? Si es así, por saberlo y cerrar el hilo, y sino, para intentar solventar el bug entre los dos.

**Comment by santiis2010** [comment]
> Hola Santiago, al final, diste con el problema? Si es así, por saberlo y cerrar el hilo, y sino, para intentar solventar el bug entre los dos.

Hola David, justo te iba a responder y vi mensaje, lleve la impresora al Service de Anet en Uruguay, resulta que en un momento el sensor ya ni funcionaba, me dijeron que el sensor está roto, y también se "jodió" algo en la placa porque no detecta si le pones un sensor nuevo, de momento le tendré que poner un endstop, vos sabés algún esquema donde pueda ver qué componentes en la placa manejan el sensor para intentar reparar? 

En todo caso esto está resuelto ya que es tema de hardware y no de software ni firmware.

**Comment by davidtgbe** [comment]
Siento lo de la placa... 
Que yo sepa no hay un esquema tan detallado Santiago. Tendrías que seguir tu mismo las pistas en el PCB e ir comprobando que todo está en orden con ayuda de un multimetro.

**Comment by santiis2010** [comment]
Si sabes que seguí las pistas pero es raro, el hotend y la cama me dan
temperaturas de 58 y 62 grados como de ambiente, por lo tanto debe estar
jodida alguna resistencia, y algún smd del sensor de nivelación, hablé con
anet y hay escasez de chips 😕 por lo que no tienen placas silenciosas, voy
a ver si escribiéndoles a ellos me pasarían un esquema porque las pistas no
están muy claras en la olaca, igual no creo que me pasen pero bueno.

Gracias por la ayuda capo! Que andes bien
