### ISSUE TITLE
hi sir, im trying to boot the marlin into my anet et4 with openblt, but heres the thing. I cannot find the .srec file. Is there any other method i can follow?

### ISSUE THREAD

**Issue by yesilikeanything** [davidtgbe/Marlin#25]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by davidtgbe** [comment]
No, there is no other method. Read and follow tutorials and videos. There are plenty of them.
