### ISSUE TITLE
Posible corrección del problema de la activación de la calibración desde la propia pantalla táctil

### ISSUE THREAD

**Issue by ricmm71** [davidtgbe/Marlin#27]
### Description

https://github.com/MarlinFirmware/Marlin/issues/21860

El problema parece estar relacionado con que al borrar la pantalla se hace un reset del módulo que gestiona la pantalla táctil. Una manera simple que lo corrige, pero que es posible tenga otros efectos colaterales (que no he observado), es simplemente eliminado en el fichero "Marlin/Marlin/src/lcd/tft/ui_common.cpp" la línea 204 "touch.reset();" en "MarlinUI::clear_lcd()", o reemplazarla por "touch.clear() ;" (que parece más adecuado, a simpe vista ...).
Parece que tiene sentido que si el puntero sigue tocando la pantalla, como es el caso en que se activa la calibración por tenerlo pulsado varios segundos, el estado del módulo "touch" debería seguir siendo "puntero pulsado", y no hacer un reset.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by davidtgbe** [comment]
Hola @ricmm71, muchas gracias por solución! y perdona por la tardanza. He tenido unas cuantas cosas entre manos y no he tocado la impresora.
He añadido touch.clear() y parece que va bien. No lo he probado extensivamente pero el problema queda resuelto aparentemente sin romper ninguna otra cosa.
