### ISSUE TITLE
deprecated definition Z_PROBE_SPEED_SLOW

### ISSUE THREAD

**Issue by tungbuivn** [davidtgbe/Marlin#28]
### Description
the declare Z_PROBE_SPEED_SLOW in the anet et4x has ineffect, it has been replaced in the bugfix branch. Here is the source from Marlin\src\inc\SanityCheck.h
![image](https://user-images.githubusercontent.com/2397798/158333685-8b947f71-962b-4a7e-b67e-7d22849b6d06.png)

the source line from configuration.h of anet et4x
#define Z_PROBE_SPEED_SLOW (Z_PROBE_SPEED_FAST / 4)
should be replace with:
#define Z_PROBE_FEEDRATE_SLOW (Z_PROBE_FEEDRATE_FAST / 4
i also re-synchonire anet-et4x configuration file to match configuration in the root of marlin folder and keep setting of the "anet4x". please approve it when you have free time.
[updateConfig.txt](https://github.com/davidtgbe/Marlin/files/8252064/updateConfig.txt)
)

**Comment by davidtgbe** [comment]
Updated
