### ISSUE TITLE
BONJOUR JE NE COMPREND PAS POURQUOI LE TACTIL DE MON ECRAN NE FONCTIONNE PAS BIEN DUTOUT ANET ET5X POUVAIS VOUS MAIDER SVP ?

### ISSUE THREAD

**Issue by LUDO19931011** [davidtgbe/Marlin#29]
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by maumontel** [comment]
Try a M995 (https://marlinfw.org/docs/gcode/M995.html) from a computer.
