### ISSUE TITLE
[FR] Anet A8 V2

### ISSUE THREAD

**Issue by yonitjio** [davidtgbe/Marlin#31]
### Is your feature request related to a problem? Please describe.

This is not really an ET4/ET5's issue. I want to find out if I can use it with Anet A8 V2.

### Are you looking for hardware support?

Printer: Anet A8 V2.
Board: Stock Anet A8 V2 (A8 V2_V2.0).
![Anet A8 V2 Board](https://user-images.githubusercontent.com/22361729/214973886-7cee0920-97f6-4b4d-b6a7-275ff29da971.png)

### Describe the feature you want

Everything? 
Like a normal printer, for example they locked most of the gcodes, calibration, report, etc.

### Additional context

I'm new in 3d printing, so I don't know what to do. After searching information these are what I got:
1. It's not clear if this model is officially released or not. Someone said on FB group that this model is sold only from local seller, practically there are no support. This I have experienced it myself. I tried emailing Anet and post on FB group but there was no reply.
2. As you can see from the board it's STM32 chip. This is why I want to found out if I can use marlin with it.
3. It uses ET4 screen.

**Comment by davidtgbe** [comment]
You can try. MCU is the same so I think at least marlin will load. If MCU inputs/outputs are connected the same way as ET4/5 it will work.
