### ISSUE TITLE
Auto Print Cancellation

### ISSUE THREAD

**Issue by ghost** [davidtgbe/Marlin#34]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

After 3-4 minutes of printing is cancel itself 

### Bug Timeline

09.06.2023

### Steps to Reproduce

1. I sliced some testprints
2. Posted them on the sd card
3. Preheat the printer: 235/75
4. Printed 3 minutes and print cancels

### Version of Marlin Firmware

bugfix-2.1.x

### Printer model

Anet ET4xr

### Electronics

Stock

### Add-ons

PrintHead Case

### Bed Leveling

None

### Your Slicer

None

### Host Software

None

### Don't forget to include

- [x] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

https://github.com/davidtgbe/Marlin/assets/100967548/7417e46c-a749-4317-b225-1fc484d37db0

[Marlin (2).zip](https://github.com/davidtgbe/Marlin/files/11734454/Marlin.2.zip)

**Comment by ghost** [comment]
Now Im using olser version of firmware, there isnt problems

**Comment by davidtgbe** [comment]
@DRed002 I have no experienced those symptoms with any release, but, to be honest  I haven't print anything for a long time. Anyway,  I have just uploaded a new merge and I'm printing now from SD. No problems so far.
