### ISSUE TITLE
Question: Programming with a Raspberry PI

### ISSUE THREAD

**Issue by 1uknowleast** [davidtgbe/Marlin#5]
Hi

Do you think you could program the board with a raspberry pi and STM32FLASH?

**Comment by Moody66** [comment]
> STM32FLASH

https://fishpepper.de/2016/09/16/installing-using-st-link-v2-to-flash-stm32-on-linux/

**Comment by davidtgbe** [comment]
@1uknowleast Yes, you can use anything that works for flashing thorugh SWD. But, for the price (clones), it's more practical to use a flahser like st-link or j-link.
